### ISSUE TITLE
Merge Lumisection/Runs apps into one app

### ISSUE THREAD

**Issue by nothingface0** [CMSTrackerDPG/MLplayground#20]

**Comment by Abhit03** [comment]
@XavierAtCERN 
Me and @nothingface0 discussed regarding merging the `Run` and `Lumisection` models into one since it will allow us to group things into `Tasks`. But our questions is what do we call it ? e.g. `Event` (Since they have an associated timeframe in which they occur), but of course it may be misleading with the CMS term `Event`. So any suggestions would be nice.

**Comment by nothingface0** [comment]
After discussion, proceeding with an app named `data_taking_objects`!
